 //static data
 export const trainings = [
    {
      image: "certification-training.png",
      title: "Language Arts",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "3",
      lectures: "5",
      level: "Beginner",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
    {
      image: "pmp-certification-training.png",
      title: "Mathematics",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "30",
      lectures: "34",
      level: "Average",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
    {
      image: "certification-training.png",
      title: "Science",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: false,
      status: "start",
    },
    {
      image: "certification-training.png",
      title: "Social Studies",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: true,
      status: "start",
    },
    {
      image: "certification-training.png",
      title: "Elective courses",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
    {
      image: "certification-training.png",
      title: "Art",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
  ];