import { StoreProvider } from "@/redux/StoreProvider";
import "./globals.css";
import { Providers } from "./providers";
import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/bundle";
import Login from "@/components/homepage/Login";
import SignUp from "@/components/homepage/Signup";

// static
// export const metadata: Metadata = {
//   title: "Myattacademy",
//   description: "Generated by create next app",
// };

// dynamic
export async function generateMetadata({ params }: any) {
  // console.log({ params });

  return {
    title: {
      template: "Myattacademy",
      default: "Gateway to Excellence in Online Education and Homeschooling", // a default is required when creating a template
    },
    description:
      "Explore a world of possibilities with our online homeschool programs and curriculum. We offer top-notch online education, learning platforms, and elementary to high school courses. Join our academy online for the best in virtual learning!",
    openGraph: {
      title: {
        template: "Myattacademy",
        default: "Gateway to Excellence in Online Education and Homeschooling", // a default is required when creating a template
      },
      description:
        "Explore a world of possibilities with our online homeschool programs and curriculum. We offer top-notch online education, learning platforms, and elementary to high school courses. Join our academy online for the best in virtual learning!",
      url: process.env.DOMAIN,
      siteName: "Myattacademy",
      // images: [
      //   {
      //     url: "https://nextjs.org/og.png",
      //     width: 800,
      //     height: 600,
      //   },
      //   {
      //     url: "https://nextjs.org/og-alt.png",
      //     width: 1800,
      //     height: 1600,
      //     alt: "My custom alt",
      //   },
      // ],
      // locale: "en_US",
      type: "website",
      // robots: {
      //   index: false,
      //   follow: true,
      //   nocache: true,
      //   googleBot: {
      //     index: true,
      //     follow: false,
      //     noimageindex: true,
      //     "max-video-preview": -1,
      //     "max-image-preview": "large",
      //     "max-snippet": -1,
      //   },
      // },
    },
    twitter: {
      card: "summary_large_image", // card
      title: "Myattacademy",
      description:
        "Explore a world of possibilities with our online homeschool programs and curriculum. We offer top-notch online education, learning platforms, and elementary to high school courses. Join our academy online for the best in virtual learning!",
      // siteId: "1467726470533754880",
      creator: "Myattacademy",
      // creatorId: "1467726470533754880",
      // images: {
      //   url: "https://nextjs.org/og.png",
      //   alt: "Next.js Logo",
      // },
      // app: {
      //   name: "twitter_app",
      //   id: {
      //     iphone: "twitter_app://iphone",
      //     ipad: "twitter_app://ipad",
      //     googleplay: "twitter_app://googleplay",
      //   },
      //   url: {
      //     iphone: "https://iphone_url",
      //     ipad: "https://ipad_url",
      //   },
      // },
    },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Providers>
            {children}
            <Login />
            <SignUp />
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
