
//static data
export const trainings = [
    {
      image: "certification-training.png",
      title: "Certification Training",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "3",
      lectures: "5",
      level: "Beginner",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
    {
      image: "pmp-certification-training.png",
      title: "PMP Certification Training",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "30",
      lectures: "34",
      level: "Average",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
    {
      image: "certification-training.png",
      title: "Certificatin Training",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: true,
      status: "inprogress",
    },
    {
      image: "certification-training.png",
      title: "Certificatin Training",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: false,
      status: "start",
    },
    {
      image: "certification-training.png",
      title: "Certificatin Training",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: true,
      status: "start",
    },
    {
      image: "certification-training.png",
      title: "Certificatin Training",
      trainer: "Ms. Honey Sheen Demogena",
      hours: "9",
      lectures: "20",
      level: "Intermediate",
      price: "50",
      isFav: false,
      status: "inprogress",
    },
  ];
  //static data end
  